# Generated by Django 5.0.4 on 2024-05-03 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroContabilidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('valor', models.FloatField()),
                ('vehiculo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparto.vehiculo', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=False)),
                ('vehiculo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparto.vehiculo', unique=True)),
            ],
        ),
    ]
