# Generated by Django 5.0.4 on 2024-05-03 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='vehiculo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparto.vehiculo'),
        ),
        migrations.AlterField(
            model_name='registrocontabilidad',
            name='vehiculo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparto.vehiculo'),
        ),
    ]
